name: backend tests

on:
  push:
    paths:
      - "backend/**"
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./gradlew test
        continue-on-error: true
